# Generated by cucumber-sinatra. (2011-06-28 23:40:59 +1000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Application

class ApplicationWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ApplicationWorld.new
end
